#Configuraci√≥n de Desarrollo de Docker-Compose
version: '3.8'

services:
  api:
    #hereda todo de base.api
    volumes:
      - ./docker/app:/app/app
    #y expone el puerto en dev
    ports:
      - "8080:8080"
